name: CI

on: [push]

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - uses: php-actions/composer@v1
    - name: Run tests with phpunit
      run: vendor/bin/phpunit --coverage-clover coverage.xml
    - name: "Send code coverage report to Codecov.io"
      env:
          CODECOV_TOKEN: "${{ secrets.CODECOV_TOKEN }}"
      run: "bash <(curl -s https://codecov.io/bash)"
